# Generated by Django 4.1 on 2023-12-12 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PKnowledge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("condition", models.CharField(max_length=255)),
                ("outcome", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "过程知识",
                "verbose_name_plural": "05.过程知识列表",
            },
        ),
        migrations.CreateModel(
            name="ReactorModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "堆型号",
                "verbose_name_plural": "01.堆型号",
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "任务",
                "verbose_name_plural": "02.任务列表",
            },
        ),
        migrations.CreateModel(
            name="TrunkType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "知识类别",
                "verbose_name_plural": "03.知识类别",
            },
        ),
        migrations.CreateModel(
            name="DKnowledge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "reactormodel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactormodel",
                        to="coper.reactormodel",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task",
                        to="coper.task",
                    ),
                ),
                (
                    "trunktype",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trunktype",
                        to="coper.trunktype",
                    ),
                ),
            ],
            options={
                "verbose_name": "陈述知识",
                "verbose_name_plural": "04.陈述列表",
            },
        ),
        migrations.CreateModel(
            name="CognitiveModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("author", models.CharField(max_length=255)),
                ("taskname", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("production", models.ManyToManyField(to="coper.pknowledge")),
            ],
            options={
                "verbose_name": "认知模型",
                "verbose_name_plural": "06.认知模型",
            },
        ),
    ]
